item { 
	name:'UpArrow'
	id:1
}
item { 
	name:'DownArrow'
	id:2
}
item { 
	name:'RightArrow'
	id:3
}
item { 
	name:'LeftArrow'
	id:4
}
item { 
	name:'Go'
	id:5
}
item { 
	name:'Six'
	id:6
}
item { 
	name:'Seven'
	id:7
}
item { 
	name:'Eight'
	id:8
}
item { 
	name:'Nine'
	id:9
}
item { 
	name:'Zero'
	id:10
}
item { 
	name:'AlphabetV'
	id:11
}
item { 
	name:'AlphabetW'
	id:12
}
item { 
	name:'AlphabetX'
	id:13
}
item { 
	name:'AlphabetY'
	id:14
}
item { 
	name:'AlphabetZ'
	id:15
}
item { 
	name:'BullsEye'
	id:16
}
